services:
  postgres:
    image: postgres:16
    container_name: devices-postgres
    environment:
      POSTGRES_USER: devices
      POSTGRES_PASSWORD: AQalqlNM9
      POSTGRES_DB: devicesdb
    ports:
      - "5432:5432"
    volumes:
      - devices_pgdata:/var/lib/postgresql/data

volumes:
  devices_pgdata: